### ISSUE TITLE
MVP / V1 Release TODO

### ISSUE THREAD

**Issue by Sonata26** [G3Kappa/KeeperRL-Technofac#12]
**MVP**:
A lone keeper that creates factories consisting of conveyor belts, drills, and assemblers. For minions, the keeper has to produce robot parts using the factory and assemble them. No special win condition at this point or anything too fancy.

## TODO:
**Structures**
- [x] New conveyor sprites
- [ ] Splitters

**Crafting**
- [ ] List of assembling machines
- [ ] List of Recipes
- [ ] Sprites for the recipes and machines
- [ ] Functionality for them

**Minions**
- [ ] Design/Lore ideas for the robots (does anyone have a favorite style of robots?)
- [ ] Worker Robot (for the initial mining and hauling)
- [ ] A few types of combat robots (if we do them like gnome automaton we just need a few types of parts)

**Misc**
- [ ] New resource: Copper (for making components and maybe we can have it be drillable only)

## Lists
**Assembling Machine List**
- [ ] Component/Electronics assembler
- [ ] Robotics assembler (for robot parts, but how do we handle lots of different parts? Maybe it can be for assembling the body and the keeper crafts the other parts by hand?)
- [ ] Incenerator

**Recipe List**
- [ ] Components: Copper + Iron

**Keeper Equipment List**
- [ ] Teleporter pack
- [ ] Exoskeleton Suit
- [ ] Cloaking Device
- [ ] Shield Pack (2 types: Projectile/Heat for Ranged/Magic)
- [ ] Bionic limbs (as equipment)

**Robotic Parts**
- Sphere Drones (mostly for maintenace)
  - [ ] Light Frame, Heavy Frame
  - [ ] Construction Arms, Repair Arms
  - [ ] Basic turret
  - [ ] Mining Laser

- Triangular Drones (more of a magic based robot?)
  - [ ] Spacial Displacement Module (teleportation)
  - [ ] Black Hole Storage (infinite carrying capacity)
  - [ ] Some type of laser

- Humanoid Robots
  - [ ] Jetpacks (flying attribute)
  - [ ] Light/Heavy
  - [ ] Arm cannons (laser, incendiary, explosive)
  - [ ] Blade arms (for melee)
  - [ ] Standard legs, Tank Treads
  - [ ] Self Destruct Module (like the goblin bombers)

**Comment by GameDungeon** [comment]
We can do the Drill Down / Quarry One

**Comment by G3Kappa** [comment]
- Ore tiles should have a different destroyedEffect that spawns a "floor ore tile" instead of dropping resources. These tiles can then be mined with drills.

**Comment by giovinazzo-kevin** [comment]
Teleportation would be tricky, I think. There's no effect that lets you move minions around, aside from **Audience**, which is the throne's effect, and **Jump** which can't be controlled. I could be wrong on this one, but that's what my earlier tests showed unfortunately.

**Comment by Sonata26** [comment]
> Teleportation would be tricky, I think. There's no effect that lets you move minions around, aside from **Audience**, which is the throne's effect, and **Jump** which can't be controlled. I could be wrong on this one, but that's what my earlier tests showed unfortunately.

You can't filter and use the "Escape" effect on them?

**Comment by GameDungeon** [comment]
I think he meant escape here, "**Jump** which can't be controlled" There is a controlled teleport spell.

**Comment by giovinazzo-kevin** [comment]
Yeah there's also Jump, but Escape has the same problem of being uncontrolled.
